# Generated by Django 2.1.7 on 2019-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopluarPostNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default=None, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default=None, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(default=None)),
            ],
        ),
    ]
