# Generated by Django 2.1.7 on 2019-03-10 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopluarPostNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.TopNews'),
        ),
    ]
