# Generated by Django 2.1.7 on 2019-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='author',
            field=models.CharField(default=None, max_length=90),
        ),
        migrations.AddField(
            model_name='topnews',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='topnews',
            name='featured',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='topnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
