# Generated by Django 2.1.7 on 2019-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popluarpostnews',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='recentnews',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100),
        ),
    ]
