# Generated by Django 2.1.7 on 2019-03-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190308_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popluarpostnews',
            name='slug',
            field=models.SlugField(blank=True, default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='recentnews',
            name='slug',
            field=models.SlugField(blank=True, default=None, unique=True),
        ),
    ]
