# Generated by Django 2.1.7 on 2019-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190309_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lokswar/')),
                ('author', models.CharField(default=None, max_length=90)),
                ('date', models.DateTimeField(blank=True, default=None)),
                ('featured', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
