# Generated by Django 2.1.7 on 2019-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lokswar/'),
        ),
        migrations.AlterField(
            model_name='popluarpostnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lokswar/'),
        ),
        migrations.AlterField(
            model_name='recentnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lokswar/'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lokswar/'),
        ),
    ]
