# Generated by Django 2.1.7 on 2019-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='politics',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='popluarpostnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='recentnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='upload_image_path'),
        ),
    ]
