# Generated by Django 2.1.3 on 2019-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_videonews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='\\img'),
        ),
    ]
