# Generated by Django 2.1.7 on 2019-03-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190307_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='popluarpostnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lokswar/'),
        ),
        migrations.AlterField(
            model_name='recentnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lokswar/'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lokswar/'),
        ),
    ]
