# Generated by Django 2.1.7 on 2019-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190308_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='slug',
            field=models.SlugField(blank=True, default=True, unique=True),
        ),
    ]
